# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Change_delayreason.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(264, 239)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.spoolSelected_Label = QtWidgets.QLabel(Dialog)
        self.spoolSelected_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spoolSelected_Label.setObjectName("spoolSelected_Label")
        self.gridLayout.addWidget(self.spoolSelected_Label, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.System_Label = QtWidgets.QLabel(Dialog)
        self.System_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.System_Label.setObjectName("System_Label")
        self.gridLayout.addWidget(self.System_Label, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.Module_Label = QtWidgets.QLabel(Dialog)
        self.Module_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Module_Label.setObjectName("Module_Label")
        self.gridLayout.addWidget(self.Module_Label, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.currentDelay_Label = QtWidgets.QLabel(Dialog)
        self.currentDelay_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentDelay_Label.setObjectName("currentDelay_Label")
        self.gridLayout.addWidget(self.currentDelay_Label, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.NewDelayReason_comboBox = QtWidgets.QComboBox(Dialog)
        self.NewDelayReason_comboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.NewDelayReason_comboBox.setEditable(True)
        self.NewDelayReason_comboBox.setObjectName("NewDelayReason_comboBox")
        self.gridLayout.addWidget(self.NewDelayReason_comboBox, 4, 1, 1, 1)
        self.save_pushButton = QtWidgets.QPushButton(Dialog)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.Delay_startDate_toolButton = QtWidgets.QToolButton(Dialog)
        self.Delay_startDate_toolButton.setObjectName("Delay_startDate_toolButton")
        self.gridLayout.addWidget(self.Delay_startDate_toolButton, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.delay_enddate_toolButton = QtWidgets.QToolButton(Dialog)
        self.delay_enddate_toolButton.setObjectName("delay_enddate_toolButton")
        self.gridLayout.addWidget(self.delay_enddate_toolButton, 7, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Spool:"))
        self.spoolSelected_Label.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "System:"))
        self.System_Label.setText(_translate("Dialog", "TextLabel"))
        self.label_10.setText(_translate("Dialog", "Module:"))
        self.Module_Label.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "Current Delay Reason:"))
        self.currentDelay_Label.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "New Delay Reason:"))
        self.save_pushButton.setText(_translate("Dialog", "Save"))
        self.label_3.setText(_translate("Dialog", "Delay Start Date:"))
        self.Delay_startDate_toolButton.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Delay End Date:"))
        self.delay_enddate_toolButton.setText(_translate("Dialog", "..."))
