# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePOC_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(325, 234)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spoolSelected_Label = QtWidgets.QLabel(Dialog)
        self.spoolSelected_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spoolSelected_Label.setObjectName("spoolSelected_Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spoolSelected_Label)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.System_Label = QtWidgets.QLabel(Dialog)
        self.System_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.System_Label.setObjectName("System_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.System_Label)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.Module_Label = QtWidgets.QLabel(Dialog)
        self.Module_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Module_Label.setObjectName("Module_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Module_Label)
        self.currentPOC_Label = QtWidgets.QLabel(Dialog)
        self.currentPOC_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentPOC_Label.setObjectName("currentPOC_Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.currentPOC_Label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.NewPOC_comboBox = QtWidgets.QComboBox(Dialog)
        self.NewPOC_comboBox.setEditable(True)
        self.NewPOC_comboBox.setObjectName("NewPOC_comboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.NewPOC_comboBox)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.delay_start_Date_toolButton = QtWidgets.QToolButton(Dialog)
        self.delay_start_Date_toolButton.setObjectName("delay_start_Date_toolButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.delay_start_Date_toolButton)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.delay_EndDate_toolButton = QtWidgets.QToolButton(Dialog)
        self.delay_EndDate_toolButton.setObjectName("delay_EndDate_toolButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.delay_EndDate_toolButton)
        self.save_pushButton = QtWidgets.QPushButton(Dialog)
        self.save_pushButton.setObjectName("save_pushButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.save_pushButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Spool:"))
        self.spoolSelected_Label.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "System:"))
        self.System_Label.setText(_translate("Dialog", "TextLabel"))
        self.label_10.setText(_translate("Dialog", "Module:"))
        self.Module_Label.setText(_translate("Dialog", "TextLabel"))
        self.currentPOC_Label.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "New Point of Construction:"))
        self.label_3.setText(_translate("Dialog", "Delay Start Date:"))
        self.delay_start_Date_toolButton.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Delay End Date:"))
        self.delay_EndDate_toolButton.setText(_translate("Dialog", "..."))
        self.save_pushButton.setText(_translate("Dialog", "Save"))
        self.label.setText(_translate("Dialog", "Current Point of Construction:"))
