from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1434, 763)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 3, 0, 1, 8)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.new_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.new_pushButton.setMinimumSize(QtCore.QSize(120, 40))
        self.new_pushButton.setMaximumSize(QtCore.QSize(120, 40))
        self.new_pushButton.setObjectName("new_pushButton")
        self.gridLayout_5.addWidget(self.new_pushButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(888, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.Export_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Export_pushButton.setMinimumSize(QtCore.QSize(120, 40))
        self.Export_pushButton.setMaximumSize(QtCore.QSize(120, 40))
        self.Export_pushButton.setObjectName("Export_pushButton")
        self.gridLayout_5.addWidget(self.Export_pushButton, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 4, 0, 1, 8)
        self.Reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.Reset_pushButton.setObjectName("Reset_pushButton")
        self.gridLayout_3.addWidget(self.Reset_pushButton, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(653, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 5, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.delayStatus_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.delayStatus_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.delayStatus_lineEdit.setObjectName("delayStatus_lineEdit")
        self.gridLayout.addWidget(self.delayStatus_lineEdit, 2, 1, 1, 1)
        self.stageofengineer_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.stageofengineer_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.stageofengineer_lineEdit.setObjectName("stageofengineer_lineEdit")
        self.gridLayout.addWidget(self.stageofengineer_lineEdit, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.targetCompletionDate_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.targetCompletionDate_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.targetCompletionDate_lineEdit.setObjectName("targetCompletionDate_lineEdit")
        self.gridLayout.addWidget(self.targetCompletionDate_lineEdit, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.spool_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.spool_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.spool_lineEdit.setObjectName("spool_lineEdit")
        self.gridLayout.addWidget(self.spool_lineEdit, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 6, 1, 1)
        self.apply_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.apply_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.gridLayout_3.addWidget(self.apply_pushButton, 2, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(321, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.Project_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Project_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Project_lineEdit.setObjectName("Project_lineEdit")
        self.gridLayout_2.addWidget(self.Project_lineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.vessel_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.vessel_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.vessel_lineEdit.setObjectName("vessel_lineEdit")
        self.gridLayout_2.addWidget(self.vessel_lineEdit, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.module_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.module_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.module_lineEdit.setObjectName("module_lineEdit")
        self.gridLayout_2.addWidget(self.module_lineEdit, 2, 1, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 2, 1)
        self.system_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.system_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.system_lineEdit.setObjectName("system_lineEdit")
        self.gridLayout_2.addWidget(self.system_lineEdit, 4, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(551, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_pushButton.setText(_translate("MainWindow", "New"))
        self.Export_pushButton.setText(_translate("MainWindow", "Export Excel"))
        self.Reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.label_11.setText(_translate("MainWindow", "Stage of Construction:"))
        self.label_12.setText(_translate("MainWindow", "Target Completion Date:"))
        self.label_10.setText(_translate("MainWindow", "Delay Status:"))
        self.label_6.setText(_translate("MainWindow", "Spool:"))
        self.apply_pushButton.setText(_translate("MainWindow", "Apply"))
        self.label.setText(_translate("MainWindow", "Status of All Pipe Spools"))
        self.label_2.setText(_translate("MainWindow", "Project:"))
        self.label_3.setText(_translate("MainWindow", "Vessel:"))
        self.label_4.setText(_translate("MainWindow", "Module:"))
        self.label_5.setText(_translate("MainWindow", "System:"))


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(MainWindow, self).__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.new_pushButton.clicked.connect(self.newpipe_spoolentry_clicked)
        self.ui.Reset_pushButton.clicked.connect(self.resetfilter_clicked)

    def newpipe_spoolentry_clicked(self):
        print(4)

    def resetfilter_clicked(self):
        print("fuck you")










