# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'POC_Delay_History.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1444, 840)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(30, -1, 30, -1)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 5, 1, 1)
        self.Delay_tableWidget = QtWidgets.QTableWidget(Dialog)
        self.Delay_tableWidget.setObjectName("Delay_tableWidget")
        self.Delay_tableWidget.setColumnCount(0)
        self.Delay_tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.Delay_tableWidget, 1, 3, 1, 3)
        self.ChangePOC_pushButton = QtWidgets.QPushButton(Dialog)
        self.ChangePOC_pushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.ChangePOC_pushButton.setMaximumSize(QtCore.QSize(250, 50))
        self.ChangePOC_pushButton.setObjectName("ChangePOC_pushButton")
        self.gridLayout.addWidget(self.ChangePOC_pushButton, 2, 1, 1, 1)
        self.ChangeDelay_pushButton = QtWidgets.QPushButton(Dialog)
        self.ChangeDelay_pushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.ChangeDelay_pushButton.setMaximumSize(QtCore.QSize(250, 50))
        self.ChangeDelay_pushButton.setObjectName("ChangeDelay_pushButton")
        self.gridLayout.addWidget(self.ChangeDelay_pushButton, 2, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)
        self.POC_tableWidget = QtWidgets.QTableWidget(Dialog)
        self.POC_tableWidget.setObjectName("POC_tableWidget")
        self.POC_tableWidget.setColumnCount(0)
        self.POC_tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.POC_tableWidget, 1, 0, 1, 3)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ChangePOC_pushButton.setText(_translate("Dialog", "Change Point of Construction"))
        self.ChangeDelay_pushButton.setText(_translate("Dialog", "Change Delay Status"))
        self.label.setText(_translate("Dialog", "Point of Construction Log"))
        self.label_2.setText(_translate("Dialog", "Delay Log"))
